name: Publish VS Code Extension

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Get version from package.json
        id: get_version
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and package the extension
        run: |
          yarn compile
          yarn global add @vscode/vsce
          mkdir -p dist/releases
          vsce package

      - name: Create a Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}

      - name: Upload Extension as Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: azure-pipelines-tasks-debugger-${{ steps.get_version.outputs.version }}.vsix
