name: Publish VS Code Extension

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
env:
  extension-name: pipelines-tasks-devkit-${{ github.ref_name }}.vsix

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and package the extension
        run: |
          yarn compile
          yarn global add @vscode/vsce
          vsce package -o ${{ env.extension-name }}

      - name: Get asset upload URL
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Extension as Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ env.extension-name }}
          asset_name: ${{ env.extension-name }}
          asset_content_type: application/octet-stream
